### ISSUE TITLE
HttpException

### ISSUE THREAD

**Issue by kkrishnan90** [CloudRail/cloudrail-si-android-sdk#10]
Hi Florian, 
I've been trying to integrate Facebook method of login but fails at every instant. I'm not able to recognise the mistakes as I've exactly followed your github readme notes. Please find the activity code and log output below

```
final Profile profile=new Facebook(MainActivity.this,"APP_ID","APP_SECRET");
        fbButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                new Thread() {
                    @Override
                    public void run() {
                        profile.login();
                        Log.e("Profile",profile.getIdentifier());
                        fullName=profile.getFullName();
                        profileemail=profile.toString();
                        Log.e("Main",fullName);
                    }
                }.start();

            }
        });

```
```
E/AndroidRuntime: FATAL EXCEPTION: Thread-5002
                                                                  Process: social.sociallogin, PID: 5117
                                                                  com.cloudrail.si.exceptions.HttpException
                                                                      at com.cloudrail.si.services.Facebook.login(Facebook.java:453)
                                                                      at social.sociallogin.MainActivity$1$1.run(MainActivity.java:44)
```

Seeking your help again. :D

**Comment by FlorianWendel** [comment]
Hmm, I can't see something wrong with your code so I'll have to ask a couple of questions:
Do you get any more details about the error stack?
Does the WebView window open to let the user login?
If so, is there any error displayed in there?

**Comment by kkrishnan90** [comment]
Hi Florian, 
See, the first time I run this app on my device (after compiling), it takes me to the Facebook authentication webview. But once I hit the login button on the webview after providing my credentials , it tries to come back to the activity screen and crashes. 
I only get this log output every time I try.

**Comment by kkrishnan90** [comment]
```
05-28 12:14:19.643 23044-23044/social.sociallogin I/ViewRootImpl: CPU Rendering VSync enable = true
05-28 12:14:19.646 23044-23409/social.sociallogin D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
05-28 12:14:19.655 23044-23044/social.sociallogin D/Atlas: Validating map...
05-28 12:14:19.711 23044-23409/social.sociallogin I/Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8916_32_LA.BR.1.2.4_RB1__release_AU (Ibddc658e36)
                                                                OpenGL ES Shader Compiler Version: E031.25.03.04
                                                                Build Date: 10/13/15 Tue
                                                                Local Branch: mybranch15212261
                                                                Remote Branch: quic/LA.BR.1.2.4_rb1.24
                                                                Local Patches: NONE
                                                                Reconstruct Branch: NOTHING
05-28 12:14:19.712 23044-23409/social.sociallogin I/OpenGLRenderer: Initialized EGL, version 1.4
05-28 12:14:19.733 23044-23409/social.sociallogin D/OpenGLRenderer: Enabling debug mode 0
05-28 12:14:19.870 23044-23044/social.sociallogin I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@28b72b86 time:7807345
05-28 12:14:24.157 23044-23044/social.sociallogin I/Timeline: Timeline: Activity_launch_request id:social.sociallogin time:7811632
05-28 12:14:24.216 23044-23044/social.sociallogin I/WebViewFactory: Loading com.google.android.webview version 50.0.2661.86 (code 266108600)
05-28 12:14:24.236 23044-23044/social.sociallogin I/cr_LibraryLoader: Time to load native libraries: 3 ms (timestamps 1708-1711)
05-28 12:14:24.236 23044-23044/social.sociallogin I/cr_LibraryLoader: Expected native library version number "50.0.2661.86", actual native library version number "50.0.2661.86"
05-28 12:14:24.266 23044-23044/social.sociallogin V/WebViewChromiumFactoryProvider: Binding Chromium to main looper Looper (main, tid 1) {2dddee5b}
05-28 12:14:24.266 23044-23044/social.sociallogin I/cr_LibraryLoader: Expected native library version number "50.0.2661.86", actual native library version number "50.0.2661.86"
05-28 12:14:24.267 23044-23044/social.sociallogin I/chromium: [INFO:library_loader_hooks.cc(143)] Chromium logging enabled: level = 0, default verbosity = 0
05-28 12:14:24.287 23044-23044/social.sociallogin I/cr_BrowserStartup: Initializing chromium process, singleProcess=true
05-28 12:14:24.298 23044-23044/social.sociallogin E/ApkAssets: Error while loading asset assets/natives_blob_64.bin: java.io.FileNotFoundException: assets/natives_blob_64.bin
05-28 12:14:24.299 23044-23044/social.sociallogin E/ApkAssets: Error while loading asset assets/snapshot_blob_64.bin: java.io.FileNotFoundException: assets/snapshot_blob_64.bin
05-28 12:14:24.375 23044-23562/social.sociallogin W/cr_media: Requires BLUETOOTH permission
05-28 12:14:24.415 23044-23044/social.sociallogin I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
05-28 12:14:24.415 23044-23044/social.sociallogin I/art: Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.WebViewContentsClientAdapter$WebResourceErrorImpl>
05-28 12:14:24.578 23044-23044/social.sociallogin I/art: Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingWebActionModeCallback>
05-28 12:14:24.578 23044-23044/social.sociallogin I/art: Rejecting re-init on previously-failed class java.lang.Class<org.chromium.content.browser.FloatingWebActionModeCallback>
05-28 12:14:24.619 23044-23044/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:30] Constructor
05-28 12:14:24.634 23044-23044/social.sociallogin W/cr_AwContents: onDetachedFromWindow called when already detached. Ignoring
05-28 12:14:24.635 23044-23044/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: false
05-28 12:14:24.708 23044-23044/social.sociallogin I/cr_Ime: ImeThread is not enabled.
05-28 12:14:24.749 23044-23044/social.sociallogin I/ViewRootImpl: CPU Rendering VSync enable = true
05-28 12:14:24.755 23044-23044/social.sociallogin I/Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
05-28 12:14:24.910 23044-23592/social.sociallogin E/libEGL: validate_display:255 error 3008 (EGL_BAD_DISPLAY)
05-28 12:14:24.969 23044-23044/social.sociallogin I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@12786972 time:7812443
05-28 12:14:26.074 23044-23044/social.sociallogin W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 23044
05-28 12:14:26.075 23044-23044/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: true
05-28 12:14:26.075 23044-23044/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:68] hideSoftInputFromWindow
05-28 12:14:31.580 23044-23044/social.sociallogin I/chromium: [INFO:CONSOLE(0)] "Deferred long-running timer task(s) to improve scrolling smoothness. See crbug.com/574343.", source: https://m.facebook.com/login.php?skip_api_login=1&api_key=1730424860533900&signed_next=1&next=https%3A%2F%2Fm.facebook.com%2Fv2.5%2Fdialog%2Foauth%3Fredirect_uri%3Dhttps%253A%252F%252Fwww.cloudrailauth.com%252Fauth%26state%3DCloudRailSI%26scope%3Dpublic_profile%252C%2Bemail%252C%2Buser_birthday%252C%2Buser_about_me%26response_type%3Dcode%26client_id%3D1730424860533900%26ret%3Dlogin%26logger_id%3Db4524064-5028-4a2e-8475-585564c1d940&cancel_url=https%3A%2F%2Fwww.cloudrailauth.com%2Fauth%3Ferror%3Daccess_denied%26error_code%3D200%26error_description%3DPermissions%2Berror%26error_reason%3Duser_denied%26state%3DCloudRailSI%23_%3D_&display=touch&locale=en_GB&logger_id=b4524064-5028-4a2e-8475-585564c1d940&_rdr (0)

05-28 12:14:55.751 23044-23044/social.sociallogin I/ViewRootImpl: CPU Rendering VSync enable = true
05-28 12:14:57.333 23044-23044/social.sociallogin I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@28b72b86 time:7844808
05-28 12:14:57.491 23044-23044/social.sociallogin W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 23044
05-28 12:14:57.540 23044-23044/social.sociallogin W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 23044
05-28 12:14:57.546 23044-23044/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: false
05-28 12:14:57.547 23044-23044/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:42] restartInput
05-28 12:14:57.673 23044-23044/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: false
05-28 12:14:57.673 23044-23044/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:42] restartInput
05-28 12:14:57.674 23044-23044/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:77] updateSelection: SEL [0, 0], COM [-1, -1]
                                                            
                                                            --------- beginning of crash
05-28 12:14:57.822 23044-23543/social.sociallogin E/AndroidRuntime: FATAL EXCEPTION: Thread-1433
                                                                    Process: social.sociallogin, PID: 23044
                                                                    com.cloudrail.si.exceptions.HttpException
                                                                        at com.cloudrail.si.services.Facebook.login(Facebook.java:453)
                                                                        at social.sociallogin.MainActivity$1$1.run(MainActivity.java:45)
05-28 12:14:57.847 23044-23543/social.sociallogin I/Process: Sending signal. PID: 23044 SIG: 9
```


I think this log might help you ...

**Comment by FlorianWendel** [comment]
I see. Have you verified that your client identifier and secret are correct?
Is the redirect URI properly set to "https://www.cloudrailauth.com/auth" in your Facebook app?
You'll find that this URL does not exist and it needn't since we catch the redirect directly from the WebView, but it needs to match the one used in the code exchange phase after (and there we use "https://www.cloudrailauth.com/auth") which seems to be the step that fails.

**Comment by kkrishnan90** [comment]
![image](https://cloud.githubusercontent.com/assets/8684961/15625708/0286e466-24cf-11e6-9729-c6da6278b4fe.png)
 

I have also set a proper OAuth in my Facebook Developer console.

**Comment by FlorianWendel** [comment]
Alright then, I'll have to look into this some more and ask some other people. I'll come back to you once I know more. Did you by any chance try to get any of the other Profile services running and did it work?

**Comment by kkrishnan90** [comment]
No actually I tried my first shot with Facebook, but it didn't yield me proper results. Thanks Florian, 
I'll also try other services (Profile services) and will let you know. I'll be glad if we can close this really quick, coz I'm planning to include this in my apps that are going to get deployed in a day's time.

**Comment by FlorianWendel** [comment]
To see if I could reproduce your problem I created a new project in Android studio and changed the app's build.gradle to this:


    apply plugin: 'com.android.application'

    android {
        compileSdkVersion 23
        buildToolsVersion "23.0.2"

        defaultConfig {
            applicationId "com.cloudrail.si.fbproblemtest"
            minSdkVersion 15
            targetSdkVersion 23
            versionCode 1
            versionName "1.0"
        }
        buildTypes {
            release {
                minifyEnabled false
                proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            }
        }
    }

    repositories {
        maven {
            url "http://maven.cloudrail.com"
        }
    }

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        testCompile 'junit:junit:4.12'
        compile 'com.android.support:appcompat-v7:23.4.0'
        compile 'com.cloudrail:cloudrail-si-android:2.1.0'
    }

and my MainActivity.java to this:


    package com.cloudrail.si.fbproblemtest;

    import android.os.Bundle;
    import android.support.v7.app.AppCompatActivity;
    import android.util.Log;

    import com.cloudrail.si.interfaces.Profile;
    import com.cloudrail.si.services.Facebook;

    public class MainActivity extends AppCompatActivity {

            @Override
            protected void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                setContentView(R.layout.activity_main);
                final Profile profile = new Facebook(MainActivity.this, "xxx", "xxx");
                new Thread() {
                    public void run() {
                        profile.login();
                        Log.i("ID", profile.getIdentifier());
                        Log.i("Full name", profile.getFullName() != null ? profile.getFullName() : "n/a");
                        Log.i("Email", profile.getEmail() != null ? profile.getEmail() : "n/a");
                        Log.i("Gender", profile.getGender() != null ? profile.getGender() : "n/a");
                        Log.i("Description", profile.getDescription() != null ? profile.getDescription() : "n/a");
                        Log.i("Birthday", (profile.getDateOfBirth().getDay() != null ? profile.getDateOfBirth().getDay() : "n/a") + "."
                                + (profile.getDateOfBirth().getMonth() != null ? profile.getDateOfBirth().getMonth() : "n/a") + "."
                                + (profile.getDateOfBirth().getYear() != null ? profile.getDateOfBirth().getYear() : "n/a"));
                        Log.i("Locale", profile.getLocale() != null ? profile.getLocale() : "n/a");
                        Log.i("Picture", profile.getPictureURL() != null ? profile.getPictureURL() : "n/a");
                        profile.logout();
                    }
                }.start();
            }

    }


the xxx being client identifier and secret of an app I've just created with settings exactly identical to what you showed in your screenshot. This worked fine for me, I got the right info and no crash. Could you try something similar with a new project? Maybe there is some global setting in your current project that changes the way HTTPS requests work? Or something interfering with Threads?

**Comment by kkrishnan90** [comment]
Thanks Florian, let me once again copy the exact code that you have used to replicate the problem. Could you also pls post a screenshot of the output that you get ?

**Comment by kkrishnan90** [comment]
This time, I get this Florian !

```
05-28 14:52:21.302 4119-4119/social.sociallogin E/WindowManager: android.view.WindowLeaked: Activity com.cloudrail.si.servicecode.commands.awaitCodeRedirect.AuthenticationActivity has leaked window org.chromium.content.browser.input.PopupTouchHandleDrawable{2ba227da I.ED.... ........ 0,0-40,48} that was originally added here
                                                                     at android.view.ViewRootImpl.<init>(ViewRootImpl.java:364)
                                                                     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:271)
                                                                     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                     at android.widget.PopupWindow.invokePopup(PopupWindow.java:1104)
                                                                     at android.widget.PopupWindow.showAtLocation(PopupWindow.java:933)
                                                                     at android.widget.PopupWindow.showAtLocation(PopupWindow.java:897)
                                                                     at org.chromium.content.browser.input.PopupTouchHandleDrawable.show(PopupTouchHandleDrawable.java:431)
                                                                     at org.chromium.android_webview.AwContents.nativeOnDraw(Native Method)
                                                                     at org.chromium.android_webview.AwContents.access$4500(AwContents.java:96)
                                                                     at org.chromium.android_webview.AwContents$AwViewMethodsImpl.onDraw(AwContents.java:2912)
                                                                     at org.chromium.android_webview.AwContents.onDraw(AwContents.java:1243)
                                                                     at com.android.webview.chromium.WebViewChromium.onDraw(WebViewChromium.java:1740)
                                                                     at android.webkit.WebView.onDraw(WebView.java:2393)
                                                                     at android.view.View.draw(View.java:15239)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14175)
                                                                     at android.view.View.getDisplayList(View.java:14197)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14135)
                                                                     at android.view.View.getDisplayList(View.java:14197)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14135)
                                                                     at android.view.View.getDisplayList(View.java:14197)
                                                                     at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:3390)
                                                                     at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:3369)
                                                                     at android.view.View.updateDisplayListIfDirty(View.java:14135)
                                                                     at android.view.View.getDisplayList(View.java:14197)
                                                                     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
                                                                     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
                                                                     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
                                                                     at android.view.ViewRootImpl.draw(ViewRootImpl.java:2548)
                                                                     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2364)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1994)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1073)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5903)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:773)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:586)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:556)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:759)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:135)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5268)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
05-28 14:52:21.303 4119-4119/social.sociallogin W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 4119
05-28 14:52:21.306 4119-4119/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: false
05-28 14:52:21.306 4119-4119/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:42] restartInput
05-28 14:52:21.331 4119-4119/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: false
05-28 14:52:21.331 4119-4119/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:42] restartInput
05-28 14:52:21.331 4119-4119/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:77] updateSelection: SEL [0, 0], COM [-1, -1]
05-28 14:52:21.665 4119-4283/social.sociallogin E/AndroidRuntime: FATAL EXCEPTION: Thread-2091
                                                                  Process: social.sociallogin, PID: 4119
                                                                  com.cloudrail.si.exceptions.HttpException
                                                                      at com.cloudrail.si.services.Facebook.login(Facebook.java:453)
                                                                      at social.sociallogin.MainActivity$1.run(MainActivity.java:40)
```

**Comment by kkrishnan90** [comment]
Second iteration, I get this ....

```
D/cr_Ime: [InputMethodManagerWrapper.java:77] updateSelection: SEL [14, 14], COM [-1, -1]
05-28 14:55:00.122 7215-7215/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:77] updateSelection: SEL [15, 15], COM [-1, -1]
05-28 14:55:00.437 7215-7215/social.sociallogin I/chromium: [INFO:CONSOLE(0)] "Deferred long-running timer task(s) to improve scrolling smoothness. See crbug.com/574343.", source: https://m.facebook.com/login/?cuid=AYhmapd57j6LA3LgSAVmPtUWx3WKhEkjPddp2FZ7gs73FE_nx7KxZVxuEzSdsaO7XmkN3G4Jw-Qt76XNM85CmK1fpwWq1s3MizzZZcWyfzk4ba_jCi6ADEZSbxcjBhY-NzHuwHYK6wS3fUBXxUiUOaFxUZGnf6lvhsqep5JZ9NfezFjUXLq8a2qolFqZ_eoNNvA&app_id=1730424860533900&api_key=1730424860533900&auth_token=b8410a485e741d36589b852343451379&next=https%3A%2F%2Fm.facebook.com%2Fv2.5%2Fdialog%2Foauth%3Fredirect_uri%3Dhttps%253A%252F%252Fwww.cloudrailauth.com%252Fauth%26state%3DCloudRailSI%26scope%3Dpublic_profile%252C%2Bemail%252C%2Buser_birthday%252C%2Buser_about_me%26response_type%3Dcode%26client_id%3D1730424860533900%26ret%3Dlogin%26logger_id%3Dc157c2ca-7fe5-4cc2-81c1-ff2d70991771&email=k.krishnan.90%40gmail.com&li=2WNJVy9SapP87gQxqD61voXS&lhsrc=lau_sub&e=1348092&skip_api_login=1&locale2=en_GB&refid=9&refsrc=https%3A%2F%2Fm.facebook.com%2Flogin.php&_rdr (0)
05-28 14:55:00.559 7215-7215/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:50] showSoftInput
05-28 14:55:00.560 7215-7215/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:77] updateSelection: SEL [15, 15], COM [-1, -1]
05-28 14:55:00.592 7215-7215/social.sociallogin I/ViewRootImpl: CPU Rendering VSync enable = true
05-28 14:55:01.126 7215-7215/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:77] updateSelection: SEL [15, 15], COM [-1, -1]
05-28 14:55:01.435 7215-7215/social.sociallogin W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 7215
05-28 14:55:01.458 7215-7215/social.sociallogin I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@28b72b86 time:17448933
05-28 14:55:01.462 7215-7215/social.sociallogin W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 7215
05-28 14:55:01.472 7215-7215/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: false
05-28 14:55:01.472 7215-7215/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:42] restartInput
05-28 14:55:01.498 7215-7215/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:59] isActive: false
05-28 14:55:01.498 7215-7215/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:42] restartInput
05-28 14:55:01.499 7215-7215/social.sociallogin D/cr_Ime: [InputMethodManagerWrapper.java:77] updateSelection: SEL [0, 0], COM [-1, -1]
05-28 14:55:03.139 7215-7283/social.sociallogin E/AndroidRuntime: FATAL EXCEPTION: Thread-2140
                                                                  Process: social.sociallogin, PID: 7215
                                                                  com.cloudrail.si.exceptions.HttpException
                                                                      at com.cloudrail.si.services.Facebook.login(Facebook.java:453)
                                                                      at social.sociallogin.MainActivity$1.run(MainActivity.java:39)
```


The line 39 is where I place this piece of code
profile.login();

**Comment by FlorianWendel** [comment]
If you open the URL from the third line of your output in your browser and then grant access, do you see a non-available website with the address bar showing something like this:
"https://www.cloudrailauth.com/auth?code=..."?

**Comment by kkrishnan90** [comment]
I see this when I plug in that line you've mentioned in my browser.
https://www.cloudrailauth.com/auth?code=AQBAaWs15c6P1fjJSbtqQYxL7niHSp7OxTCAfjGk9EUb_sh41LSi3E2_AAnB705GkJY5PABI4Y-7ZgaPITS-LX8jbIjnyG8EBnMHIPRcJIJVHgMG81ws0LfzoVRdUC-JbAiOmMUFK9SvWcV7s4NojgbvvWuwoP9aiz933VQokOwwbuCKp6YfcBKSNaahqswJ7CTwjXON1TmiRsEHW8FrHvwtyILmepfVlhJV6FRZDvXdLF8rzy5EA7yWNSkZWWsKmVlZgWSuvfaammKp1vBEmvesY2f1dM9gKCscNhm_jTQ6hp3HwCiNQxulWdWDaykub7WpQA2xu1I0lLhI5rpU5NJB&state=CloudRailSI#_=_

The page says , 
This site can’t be reached

www.cloudrailauth.com’s server DNS address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by FlorianWendel** [comment]
Yep, this is exactly what should happen. In my opinion this could indicate a problem with the WebView component. Just like your browser it should redirect to the exact URL you just mentioned and extract the code for further processing (ignoring the fact that the site cannot be reached). What kind of device are you testing on?

**Comment by kkrishnan90** [comment]
I'm testing in a device which runs Android 5.1.1 Lollipop .. The device is using the wifi.

**Comment by kkrishnan90** [comment]
May I know what all the permissions that is been added in the manifest.xml at your end ?
I have added INTERNET permission alone. But doesn't seem to work in another device as well which is running on Android Marshmallow.

**Comment by FlorianWendel** [comment]
Well my test app's manifest looks like this:

	<?xml version="1.0" encoding="utf-8"?>
	<manifest xmlns:android="http://schemas.android.com/apk/res/android"
	    package="com.cloudrail.si.fbproblemtest">

	    <application
	        android:allowBackup="true"
	        android:icon="@mipmap/ic_launcher"
	        android:label="@string/app_name"
	        android:supportsRtl="true"
	        android:theme="@style/AppTheme">
	        <activity android:name=".MainActivity">
	            <intent-filter>
	                <action android:name="android.intent.action.MAIN" />

	                <category android:name="android.intent.category.LAUNCHER" />
	            </intent-filter>
	        </activity>
	    </application>

	</manifest>

The necessary permissions are in the library's manifest (Internet access and registering the activity for the WebView)

**Comment by kkrishnan90** [comment]
Oh that's great ! So I need not include any permissions explicitly in my app's manifest ? That's fantastic, but unfortunately it still throws me error on the line profile.login()....Trying to figure out a way !

**Comment by FlorianWendel** [comment]
Yep that's right, when I set up this test application earlier I really only changed the MainActivity and the build.gradle, the rest was Android Studios generated defaults for a new app with an empty activity. This is why I find it so weird that the exact same thing doesn't work for you. Just tried the test with a Lollipop device and it works fine too.

**Comment by kkrishnan90** [comment]
This day is not for me ! :( Badly wanna use your library ! Let me try this out ... If possible could you please zip me your project to my email ? 
My mail ID : k.krishnan.90@gmail.com

**Comment by FlorianWendel** [comment]
Mail's out. Really hope we can figure it out.

**Comment by kkrishnan90** [comment]
Hi Florain ! I figured it out ! Probably something wrong with my code or in my Facebook Dev App Console...I created a new app in my dev console and now its working perfectly fine ! 
Thanks a ton for your continuous support !

**Comment by kkrishnan90** [comment]
You can close this issue.. Once again , a huge kudos for creating such an amazing library!

**Comment by FlorianWendel** [comment]
I'm glad it works now and thanks for your persistence!
