### ISSUE TITLE
Unable to get CloudMetaData#hashCode

### ISSUE THREAD

**Issue by VishalNehra** [CloudRail/cloudrail-si-android-sdk#112]
Getting below mentioned error when trying to execute ````CloudMetaData#hashCode```` on any of the cloud services like Dropbox, box etc

````05-22 13:28:04.648 10712-12172/com.amaze.filemanager E/GlideExecutor: Request threw uncaught throwable
    java.lang.RuntimeException: ServiceCode Error in function resolvePathRelative at 12: http.requestCall $L5 $L2 
        at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:127)
        at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45)
        at com.cloudrail.si.services.Box.getMetadata(Box.java:1071)
        at com.amaze.filemanager.filesystem.HybridFile.hashCode(HybridFile.java:1279)
        at com.amaze.filemanager.utils.glide.CloudIconModelLoader.buildLoadData(CloudIconModelLoader.java:38)
        at com.amaze.filemanager.utils.glide.CloudIconModelLoader.buildLoadData(CloudIconModelLoader.java:22)
        at com.bumptech.glide.load.engine.DecodeHelper.getLoadData(DecodeHelper.java:210)
        at com.bumptech.glide.load.engine.DecodeHelper.getCacheKeys(DecodeHelper.java:223)
        at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:42)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:266)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
     Caused by: android.os.StrictMode$StrictModeViolation: policy=262148 violation=4
        at android.os.StrictMode.executeDeathPenalty(StrictMode.java:1686)
        at android.os.StrictMode.-wrap3(Unknown Source:0)
        at android.os.StrictMode$AndroidBlockGuardPolicy.handleViolation(StrictMode.java:1679)
        at android.os.StrictMode$AndroidBlockGuardPolicy.handleViolationWithTimingAttempt(StrictMode.java:1502)
        at android.os.StrictMode$AndroidBlockGuardPolicy.startHandlingViolationException(StrictMode.java:1472)
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1457)
        at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:319)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.shutdownAndFreeSslNative(ConscryptFileDescriptorSocket.java:966)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.close(ConscryptFileDescriptorSocket.java:961)
        at com.android.okhttp.internal.Util.closeQuietly(Util.java:86)
        at com.android.okhttp.internal.http.StreamAllocation.deallocate(StreamAllocation.java:256)
        at com.android.okhttp.internal.http.StreamAllocation.connectionFailed(StreamAllocation.java:293)
        at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:445)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:509)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:244)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(Unknown Source:0)
        at com.cloudrail.si.servicecode.commands.http.RequestCall.execute(RequestCall.java:132)
        at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:87)
        at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45) 
        at com.cloudrail.si.services.Box.getMetadata(Box.java:1071) 
        at com.amaze.filemanager.filesystem.HybridFile.hashCode(HybridFile.java:1279) 
        at com.amaze.filemanager.utils.glide.CloudIconModelLoader.buildLoadData(CloudIconModelLoader.java:38) 
        at com.amaze.filemanager.utils.glide.CloudIconModelLoader.buildLoadData(CloudIconModelLoader.java:22) 
        at com.bumptech.glide.load.engine.DecodeHelper.getLoadData(DecodeHelper.java:210) 
        at com.bumptech.glide.load.engine.DecodeHelper.getCacheKeys(DecodeHelper.java:223) 
        at com.bumptech.glide.load.engine.ResourceCacheGenerator.startNext(ResourceCacheGenerator.java:42) 
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:299) 
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:266) 
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:230) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446) 
````

**Comment by PatrickStoklasa** [comment]
Can you run your application without strict mode turned on?
