### ISSUE TITLE
dropbox.Login() error

### ISSUE THREAD

**Issue by Wajeehkhan123** [CloudRail/cloudrail-si-android-sdk#124]

**Comment by Wajeehkhan123** [comment]
i  try this at from sample 
https://github.com/CloudRail/cloudrail-si-dotnet-sdk/blob/master/Examples/UnifiedBucketCloudStorage/UnifiedBucketCloudStorage/Program.cs
but getting errror
System.SystemException: ServiceCode Error in function checkAuthentication at 3: awaitCodeRedirect $L1 $L0 ? $P0.redirectUri  ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Com.CloudRail.SI.ServiceCode.Commands.AwaitCodeRedirect.Execute(Sandbox environment, Object[] parameters)
   at Com.CloudRail.SI.ServiceCode.Interpreter.Run()
   --- End of inner exception stack trace ---
   at Com.CloudRail.SI.ServiceCode.Interpreter.Run()
   at Com.CloudRail.SI.ServiceCode.Interpreter.CallFunction(String functionName, Object[] parameters)
   at Com.CloudRail.SI.Services.Dropbox.Login()
