### ISSUE TITLE
Exception when run from a scheduled service

### ISSUE THREAD

**Issue by MisterY** [CloudRail/cloudrail-si-android-sdk#32]
Hi, guys! I'm back from vacation and got another issue for you. ;)
This exception happens when the synchronization is triggered by a timer (scheduled service). 
The interesting thing is that it happens every time in the scheduled run but never when triggered from the running app (UI).

Link: https://github.com/moneymanagerex/android-money-manager-ex/issues/957

```
08-17 22:44:04.171 1526-5937/com.money.manager.ex E/SyncManager: fetching remote file info
 java.lang.RuntimeException: ServiceCode Error in function standardJSONRequest at 11
     at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:108)
     at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42)
     at com.cloudrail.si.services.Dropbox.getMetadata(Dropbox.java:889)
     at com.money.manager.ex.sync.SyncManager.loadMetadata(SyncManager.java:355)
     at com.money.manager.ex.sync.SyncService.onHandleIntent(SyncService.java:85)
     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
     at android.os.Handler.dispatchMessage(Handler.java:99)
     at android.os.Looper.loop(Looper.java:137)
     at android.os.HandlerThread.run(HandlerThread.java:60)
  Caused by: java.lang.NullPointerException
     at com.cloudrail.si.servicecode.commands.http.RequestCall.execute(RequestCall.java:113)
     at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:84)
     at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42) 
     at com.cloudrail.si.services.Dropbox.getMetadata(Dropbox.java:889) 
     at com.money.manager.ex.sync.SyncManager.loadMetadata(SyncManager.java:355) 
     at com.money.manager.ex.sync.SyncService.onHandleIntent(SyncService.java:85) 
     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65) 
     at android.os.Handler.dispatchMessage(Handler.java:99) 
     at android.os.Looper.loop(Looper.java:137) 
     at android.os.HandlerThread.run(HandlerThread.java:60) 
```

**Comment by PatrickStoklasa** [comment]
I hope you had a great time! I will try to reproduce the error and come back to you as soon as i have any news.

**Comment by MisterY** [comment]
Hi, Patrick! Thanks for the feedback.
You can always use the MMEX source if you need a test case. This issue can be observed in both `master` and `dev` branches when a periodic sync is active.

**Comment by MisterY** [comment]
Attached is the log, affecting over 300 users.

[com.money.manager.ex_issue_110_error_57b512c802c0000127a77ac40f85499a.txt](https://github.com/CloudRail/cloudrail-si-android-sdk/files/425049/com.money.manager.ex_issue_110_error_57b512c802c0000127a77ac40f85499a.txt)

**Comment by PatrickStoklasa** [comment]
The error seems to be caused by the underlying http library which seems to fail under certain conditions. The solution, at least for now, is to add a retry mechanism to the method that fails regularly. So whenever this method fails ones, retry the same method after a short delay. This seems to solve the issue.

Even though this issue is not caused by our library, we will evaluate the possibilities of doing the retry within our library! However, i consider this issue as solved.
