### ISSUE TITLE
Unknown source of exceptions

### ISSUE THREAD

**Issue by MisterY** [CloudRail/cloudrail-si-android-sdk#38]
Hi!

After upgrading to 2.6.8 and 2.7.0, I'm getting a couple of network-related exceptions that I can't trace the source to. The logs are attached below. Could the messages be improved, or could you help me identify why these happen? I'm not getting these in the emulators or the test devices but the other users do.
It looks like the exceptions happen when the library is phoning home but I'm not sure when exactly this happens in order to catch the exception. The logs do not tell me much in that respect.
Thanks!

```
Fatal Exception: java.lang.RuntimeException: ServiceCode Error in function selfTest at 26
       at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:108)
       at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42)
       at com.cloudrail.si.servicecode.InitSelfTest.execute(InitSelfTest.java:135)
       at com.cloudrail.si.servicecode.InitSelfTest.initTest(InitSelfTest.java:28)
       at com.cloudrail.si.statistics.InitSelfTestTask.run(InitSelfTestTask.java:31)
Caused by java.lang.NullPointerException
       at com.cloudrail.si.servicecode.commands.http.RequestCall.execute(RequestCall.java:120)
       at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:84)
       at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42)
       at com.cloudrail.si.servicecode.InitSelfTest.execute(InitSelfTest.java:135)
       at com.cloudrail.si.servicecode.InitSelfTest.initTest(InitSelfTest.java:28)
       at com.cloudrail.si.statistics.InitSelfTestTask.run(InitSelfTestTask.java:31)
```
and
```
Fatal Exception: java.lang.RuntimeException: ServiceCode Error in function selfTest at 26
       at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:108)
       at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42)
       at com.cloudrail.si.servicecode.InitSelfTest.execute(InitSelfTest.java:135)
       at com.cloudrail.si.servicecode.InitSelfTest.initTest(InitSelfTest.java:28)
       at com.cloudrail.si.statistics.InitSelfTestTask.run(InitSelfTestTask.java:31)
Caused by java.io.IOException: unexpected end of stream on Connection{stat-si.cloudrail.com:443, proxy=DIRECT@ hostAddress=52.29.126.102 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=http/1.1} (recycle count=0)
       at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:258)
       at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:104)
       at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:1120)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:951)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:474)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:410)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:235)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
       at com.cloudrail.si.servicecode.commands.http.RequestCall.execute(RequestCall.java:114)
       at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:84)
       at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42)
       at com.cloudrail.si.servicecode.InitSelfTest.execute(InitSelfTest.java:135)
       at com.cloudrail.si.servicecode.InitSelfTest.initTest(InitSelfTest.java:28)
       at com.cloudrail.si.statistics.InitSelfTestTask.run(InitSelfTestTask.java:31)
Caused by java.io.EOFException: \n not found: size=0 content=...
       at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
       at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:239)
       at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:104)
       at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:1120)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:951)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:474)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:410)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:235)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:25)
       at com.cloudrail.si.servicecode.commands.http.RequestCall.execute(RequestCall.java:114)
       at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:84)
       at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42)
       at com.cloudrail.si.servicecode.InitSelfTest.execute(InitSelfTest.java:135)
       at com.cloudrail.si.servicecode.InitSelfTest.initTest(InitSelfTest.java:28)
       at com.cloudrail.si.statistics.InitSelfTestTask.run(InitSelfTestTask.java:31)
```

**Comment by FlorianWendel** [comment]
Hi there,

thank you for reporting the problem. It does indeed seem to happen when the SDK is phoning home and even though I can't tell what exactly went wrong there, exceptions from failing to call home should never impact the SDK's functioning and not be visible to the user, so this is a bug.
It looks like the try-catch swallowing such exceptions got lost during making the code smaller in the latest version. We're working on a fix right now which we'll release in a few hours.

**Comment by MisterY** [comment]
Thanks! Here's one more:

```
Fatal Exception: java.lang.RuntimeException: ServiceCode Error in function selfTest at 8
       at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:108)
       at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42)
       at com.cloudrail.si.servicecode.InitSelfTest.execute(InitSelfTest.java:135)
       at com.cloudrail.si.servicecode.InitSelfTest.initTest(InitSelfTest.java:28)
       at com.cloudrail.si.statistics.InitSelfTestTask.run(InitSelfTestTask.java:31)
Caused by java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
       at com.cloudrail.si.servicecode.Sandbox.getVariable(Sandbox.java:278)
       at com.cloudrail.si.servicecode.Sandbox.getVariable(Sandbox.java:249)
       at com.cloudrail.si.servicecode.commands.Set.execute(Set.java:35)
       at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:84)
       at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42)
       at com.cloudrail.si.servicecode.InitSelfTest.execute(InitSelfTest.java:135)
       at com.cloudrail.si.servicecode.InitSelfTest.initTest(InitSelfTest.java:28)
       at com.cloudrail.si.statistics.InitSelfTestTask.run(InitSelfTestTask.java:31)
```

**Comment by MisterY** [comment]
Actually, @FlorianWendel, that was a good tip. These could have been caused by my minification, as well. 
Now I have disabled ProGuard completely in the current release. Let's see if these still happen.

**Comment by PatrickStoklasa** [comment]
The new release should fix the issue. If it doesn't, please reopen this issue.
