### ISSUE TITLE
Dropbox getChildren giving NullPointerException

### ISSUE THREAD

**Issue by donpwilson** [CloudRail/cloudrail-si-android-sdk#44]
I am using cloudrail 2.7.2.

For dropbox, service.getChildren(java.io.File.separator) is causing an null pointer exception. It used to work and still works for onedrive and box to search the root folder.

This error only happens intermittently.

`java.lang.RuntimeException: ServiceCode Error in function standardJSONRequest at 11
                                                                                at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:108)
                                                                                at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42)
                                                                                at com.cloudrail.si.services.Dropbox.getChildren(Dropbox.java:877)
                                                                                at com.dpw.photoplayer.jobs.Job_LoadCloudRailData.searchFolders(Job_LoadCloudRailData.java:146)
                                                                                at com.dpw.photoplayer.jobs.Job_LoadCloudRailData.onRun(Job_LoadCloudRailData.java:77)
                                                                                at com.birbit.android.jobqueue.Job.safeRun(Job.java:229)
                                                                                at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132)
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:398)
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:317)
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:345)
                                                                                at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36)
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:380)
                                                                                at java.lang.Thread.run(Thread.java:856)
                                                                             Caused by: java.lang.NullPointerException
                                                                                at com.cloudrail.si.servicecode.commands.http.RequestCall.execute(RequestCall.java:120)
                                                                                at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:84)
                                                                                at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:42) 
                                                                                at com.cloudrail.si.services.Dropbox.getChildren(Dropbox.java:877) 
                                                                                at com.dpw.photoplayer.jobs.Job_LoadCloudRailData.searchFolders(Job_LoadCloudRailData.java:146) 
                                                                                at com.dpw.photoplayer.jobs.Job_LoadCloudRailData.onRun(Job_LoadCloudRailData.java:77) 
                                                                                at com.birbit.android.jobqueue.Job.safeRun(Job.java:229) 
                                                                                at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132) 
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:398) 
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:317) 
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:345) 
                                                                                at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36) 
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:380) 
                                                                                at java.lang.Thread.run(Thread.java:856) `

**Comment by PatrickStoklasa** [comment]
Apart from updating the version of our SDK, did you change anything else in your code? For instance from which context the method is called? I will take a look at it though and try to find the cause of the issue.

**Comment by donpwilson** [comment]
I don't believe I've made any changes which would impact this. 

Did you see that, since posting this issue, I updated it to indicate that it only occurs intermittently. It occurred 3 times in a row which caused me to post the issue. However, since then, it has not happened at all - its been run quite a few times. Because it occurred 3 times in a row I don't think it would have been an transmission error. What I have seen since is an error message saying something like "token has expired" - I can't remember the exact wording. I amended my app so that, if there is an error logging in, to try again a couple of times. My hope with this changes is that the tokens are automatically renewed and so the next attempt to log in would work. In any case this second error has not reoccurred so the token must have been refreshed. 

So my best guess is the issue was caused somehow by a lack of permissions.

I don't want to waste your time but my suggestion would be to look at what happens, or should happen, when tokens expire and what, if anything, apps should do to cover the eventuality.

**Comment by PatrickStoklasa** [comment]
Usually the tokens returned by Dropbox do not expire unless they are revoked using the logout method or maybe by the user changing his password. However, the error message seems to be similar to the one in this issue (#32) and might have the same cause. So it seems like the http client fails for whatever reason without actually performing the request. Maybe the retry mechanism will solve the issue. If not, we can further investigate the issue.

**Comment by donpwilson** [comment]
Thanks, I'll wait and see!
