### ISSUE TITLE
Implementing access to Google Photos using the Google Drive interface

### ISSUE THREAD

**Issue by donpwilson** [CloudRail/cloudrail-si-android-sdk#64]
This follows on from the Google Photos discussion in #63.

I have been able to configure the Google Drive interface to read Google Photos by:

- replacing the default scope with "https://www.googleapis.com/auth/drive.photos.readonly" in the new option in the Google Drive constructor.
- using Advanced Requests to read the files and including "?spaces=photos" in the path.

However I have a number of residual issues:

1. When I get metadata and add a query/filter clause, I get an error in validateResponse. I've tried various different forms of syntax but cannot find one that works. Without this line I get all the metadata I want and can successfully parse it. I show below my code and the error message:

```javascript
StringBuilder builder = new StringBuilder();
            builder.append("/files?spaces=photos");
            if (pageToken != null) {
                builder.append("&pageToken=");
                builder.append(pageToken);
            }
            //TODO next line crashes
            builder.append("&q= mimeType='image/jpeg' and trashed = false");
            builder.append("&fields=nextPageToken,files(mimeType,id,name,modifiedTime,description,size," +
                    "imageMediaMetadata(height,rotation,width,time),parents,spaces,trashed)");
            AdvancedRequestSpecification specification = new AdvancedRequestSpecification(builder.toString());
            AdvancedRequestResponse response = google_drive.advancedRequest(specification);
            @SuppressWarnings("unchecked")
            Map<String, Object> resultObjectMap = (Map<String, Object>) response.getBodyJsonParsed();
            pageToken = (String) resultObjectMap.get("nextPageToken");
            @SuppressWarnings("unchecked")
            ArrayList<Map<String, Object>> filesObjectMap = ((ArrayList<Map<String, Object>>) resultObjectMap.get("files"));
        `
Java.lang.RuntimeException: ServiceCode Error in function validateResponse at 1
                                                                                at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:111)
                                                                                at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45)
                                                                                at com.cloudrail.si.services.GoogleDrive.advancedRequest(GoogleDrive.java:1820)
                                                                                at com.dpw.photoplayer.jobs.Job_LoadCloudRailData.searchForGooglePhotos(Job_LoadCloudRailData.java:196)
                                                                                at com.dpw.photoplayer.jobs.Job_LoadCloudRailData.onRun(Job_LoadCloudRailData.java:100)
                                                                                at com.birbit.android.jobqueue.Job.safeRun(Job.java:229)
                                                                                at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132)
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:407)
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:326)
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:354)
                                                                                at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36)
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:389)
                                                                                at java.lang.Thread.run(Thread.java:856)
                                                                             Caused by: com.cloudrail.si.servicecode.commands.json.jsonsimple.parser.ParseException: Unexpected character (<) at position 0.
                                                                                at com.cloudrail.si.servicecode.commands.json.jsonsimple.parser.Yylex.yylex(Yylex.java:613)
                                                                                at com.cloudrail.si.servicecode.commands.json.jsonsimple.parser.JSONParser.nextToken(JSONParser.java:269)
                                                                                at com.cloudrail.si.servicecode.commands.json.jsonsimple.parser.JSONParser.parse(JSONParser.java:118)
                                                                                at com.cloudrail.si.servicecode.commands.json.Parse.parse(Parse.java:48)
                                                                                at com.cloudrail.si.servicecode.commands.json.Parse.execute(Parse.java:38)
                                                                                at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:87)
                                                                                at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45) 
                                                                                at com.cloudrail.si.services.GoogleDrive.advancedRequest(GoogleDrive.java:1820) 
                                                                                at com.dpw.photoplayer.jobs.Job_LoadCloudRailData.searchForGooglePhotos(Job_LoadCloudRailData.java:196) 
                                                                                at com.dpw.photoplayer.jobs.Job_LoadCloudRailData.onRun(Job_LoadCloudRailData.java:100) 
                                                                                at com.birbit.android.jobqueue.Job.safeRun(Job.java:229) 
                                                                                at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132) 
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:407) 
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:326) 
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:354) 
                                                                                at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36) 
                                                                                at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:389) 
                                                                                at java.lang.Thread.run(Thread.java:856) 
```

2. I can download the thumbnail but not the full image. I suspect I've left something out that is needed either to show that I want to download the content rather than metadata or to provide sufficient authority but cannot work out what. I get an inputStream but it fails to load into an imageView, but without any exception being thrown (apart from the "fail" callback. I show below my code and also what is in the response header:

```javascript
if (model.getIsThumbnail()) {
                AdvancedRequestSpecification specification =
                        new AdvancedRequestSpecification("/files/" + model.getSourceId() +
                                "?spaces=photos&fields=thumbnailLink");
                AdvancedRequestResponse response = ((GoogleDrive) service).advancedRequest(specification);
                @SuppressWarnings("unchecked")
                Map<String, Object> parsed = (Map<String, Object>) response.getBodyJsonParsed();
                String link = (String) parsed.get("thumbnailLink");
                specification = new AdvancedRequestSpecification(link);
                specification.disableBaseUrl();
                response = ((GoogleDrive) service).advancedRequest(specification);
                input_stream = response.getBodyAsStream();
            } else {
                AdvancedRequestSpecification specification =
                        new AdvancedRequestSpecification("/files/" + model.getSourceId() + "?spaces=photos");
                AdvancedRequestResponse response = ((GoogleDrive) service).advancedRequest(specification);
                My_Utils.logW(this.getClass(), "loadData() status %s headers %s",
                        response.getStatus(), response.getHeaders().toString());
                input_stream = response.getBodyAsStream();
            }

loadData() status 200 headers {null=HTTP/1.1 200 OK, Content-Length=124, X-XSS-Protection=1; mode=block, Expires=Mon, 27 Mar 2017 10:21:15 GMT, Server=GSE, X-Content-Type-Options=nosniff, Cache-Control=private, max-age=0, must-revalidate, no-transform, X-Frame-Options=SAMEORIGIN, Alt-Svc=quic=":443"; ma=2592000; v="37,36,35", Vary=Origin, X-Origin, Date=Mon, 27 Mar 2017 10:21:15 GMT, X-Android-Received-Millis=1490610011688, Content-Type=application/json; charset=UTF-8, X-Android-Sent-Millis=1490610011507}
```
3. When setting up External Authorization, I found that the use of "singleTask" in the activity used to initiate the "Job" that does login gave me problems with logic flow between my various activities. After some investigation, I switched to use "singleTop" instead which appears to be working correctly. The activity may or may not be active when the response comes back from the browser so I authenticate the response in either "onNewIntent()" or in "onCreate()" if the intent contains "android.intent.category.BROWSABLE". In the latter case I then close the activity. Given this, I'm starting to think that the most robust generic way to handle the response is to set up an activity which is used solely for this and not to touch existing activities - with potential side effects. What do you think?

4. When granting access to Google Drive in the web browser, I an requested to allow "Have offline access". My research [http://stackoverflow.com/questions/21405274/this-app-would-like-to-have-offline-access-when-access-type-online](url) suggests that this is because I'm unnecessarily requesting a new token. Have you come across this? Is it something I need to handle in my app and if so have you any suggestions for how to proceed? Or is this something you can handle within Cloudrail?

5. Can you confirm, from your implementation of "service.getThumbnail(), that the process requires 2 requests as I have implemented it, or is there a way to do this in one step? 

Thanks in advance for your help!

**Comment by PatrickStoklasa** [comment]
Hey there,

1. I think that the issue here is that the query parameters are not URL encoded. Usually the SDK handles URL encoding of parameters but in the case of an advanced request it doesn't. So maybe running a URL encode on the value of 'q' solves the issue. In general, you can also disable the error checking in order to retrieve the response body as is by calling 'disableErrorChecking()' on the spec.

2. I think the call you are doing retrieves the photos metadata which is the reason why it can not be displayed as an image. The response header indicating the content type also says json. If memory serves correctly you can download the content by adding 'alt=media' as a query parameter.

3. Yes this would be a solution as well. Initially we wanted to do it like that within our SDK. But given the fact that the redirect URI needs to be specified by the developer we couldn't really register an intent filter within our manifest. But i think it should be totally fine if you put it into its own activity.

4. We explicitly request offline access because that is the only way that we obtain a refresh token. If we didn't you would need to reauthenticate an hour after. So we decided that the offline access would be the better option. 

5. Yes it does. We first retrieve metadata which includes the link and then do a GET request to that URL just like you do.

Hope this answers your questions.

**Comment by donpwilson** [comment]
Patrick, thanks

1. Url encoding of the query solved my issue.
2. alt:media solved my issue. I can't really understand why I didn't find this in the Google REST Api documentation but I was focused on the Reference section where it isn't mentioned. It's in Guides.
3. Thanks for the confirmation
4. I understand the dilemma. My issue is that the request for offline access is very unfriendly to a user. I might throw up a Toast when I initiate login to explain the need.
5. Thanks for the confirmation.

If you ever want a Case Study or Blog post to demonstrate this type of use of Cloudrail, I'd be happy to work with you to produce one. Just let me know.

**Comment by PatrickStoklasa** [comment]
I'm glad i could help! We would love to host a blog post about your integration. When you are done, just send me a mail to patrick@cloudrail.com and we can quickly talk about the details. 

4. Maybe there is a way to handle this via the scopes parameter but I would need to look into that again. For now you might need to go with the Toast instead.

**Comment by donpwilson** [comment]
I apologize for not producing a Case Study or Blog post as suggested above.

However, we have now been overtaken by events.

According to the Google REST API documentation pages "The photos space will sunset in early January 2018. Your users can continue to access Google Photos via the drive space by enabling the Google Photos folder in My Drive in the Drive client settings".

I only discovered this when my app access to Google Photos stopped working  today. It can still log in but when it searches for photos using "spaces=photos", none are found.

Ugh!
