### ISSUE TITLE
Further issue with External Authentication

### ISSUE THREAD

**Issue by donpwilson** [CloudRail/cloudrail-si-android-sdk#70]
If I initiate a log in using Chrome and then close the browser instead of clicking "Allow" on the permissions screen, no exception is thrown back to my app. As a result the thread that is waiting for a response waits indefinitely. This has unintended consequences in my app because the thread is independent of the "onResume()" which is triggered by the closure of the browser. It may be that this absence of an exception is more general than just this particular case. I'm not clear whether I should cover this with a timeout check or whether it is a bug.

Also, if I click "Deny" on the permissions screen I do get an exception thrown but it does not appear to be robust as it is triggered by a null object reference, see below:

```javaScript
java.lang.RuntimeException: ServiceCode Error in function authenticate at 4
                                                                               at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:111)
                                                                               at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45)
                                                                               at com.cloudrail.si.services.GoogleDrive.advancedRequest(GoogleDrive.java:1832)
                                                                               at com.dpw.photoplayer.jobs.Job_LoginToCloudRail.onRun(Job_LoginToCloudRail.java:62)
                                                                               at com.birbit.android.jobqueue.Job.safeRun(Job.java:229)
                                                                               at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132)
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:407)
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:326)
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:354)
                                                                               at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36)
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:389)
                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                            Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
                                                                               at com.cloudrail.si.servicecode.commands.string.Concat.execute(Concat.java:41)
                                                                               at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:87)
                                                                               at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45) 
                                                                               at com.cloudrail.si.services.GoogleDrive.advancedRequest(GoogleDrive.java:1832) 
                                                                               at com.dpw.photoplayer.jobs.Job_LoginToCloudRail.onRun(Job_LoginToCloudRail.java:62) 
                                                                               at com.birbit.android.jobqueue.Job.safeRun(Job.java:229) 
                                                                               at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132) 
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:407) 
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:326) 
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:354) 
                                                                               at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36) 
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:389) 
                                                                               at java.lang.Thread.run(Thread.java:818) 
`

**Comment by PatrickStoklasa** [comment]
As for the external authentication using the users standard browser i don't think there is way to reliably notice that the user has quit the process. So the only option i guess would be to handle this with a timeout. The reason why we have not implemented one ourselves is the issue of when to timeout. Some might find two minutes appropriate and some no less than ten. Is this something you agree on or do you believe it should be handled by the SDK?

I do admit that this kind of error is not very helpful. I will revisit the error cases and see how we can improve here.

**Comment by donpwilson** [comment]
I agree with the difficulty in choosing a suitable timeout lapse time. Network response times are very variable. I think it would be reasonable to add an optional timeout parameter to the login function because, if login is called, the app is requiring some form of response and an exception / login failure within the app is reasonable. I'm not sure that this would be a good extension for other functions because of the variable amount of network processing that may be needed before sending a response.

In my circumstance, the app "knows" when the user has quit the process because onResume() is called before the login callback. I therefore suggest a slightly different approach. This is to add an optional tag parameter to the login function (and maybe other functions). Then add an abort(tag) function which would trigger an Http abort() call in the appropriate syntax within Cloudrail and at the same time trigger an exception on the original call. I would call the abort function from on resume.
