### ISSUE TITLE
Throws Exception when stop social media login

### ISSUE THREAD

**Issue by danielsGit** [CloudRail/cloudrail-si-android-sdk#77]
Actually i am using explicit login feature.
Facebook fb = new Facebook(this, getString(R.string.facebook_app_id), getString(R.string.facebook_secret_key));
new Thread(new Runnable() {
                        @Override
                        public void run() {
                            fb.login();
                            signupWithSocial(GlobalUtils.FACEBOOK, fb.getFullName(), fb.getEmail());
                        }
                    }).start();

It opens facebook login page in web browser. But if i close without login, the app crashes.
 Process: sahafnraz.justhairdo, PID: 13051
  com.cloudrail.si.exceptions.AuthenticationException: Authentication was cancelled
                                                                        at com.cloudrail.si.services.Twitter.login(Twitter.java:984)
                                                                          at sahafnraz.justhairdo.RegisterActivity$5.run(RegisterActivity.java:288)
                                                                          at java.lang.Thread.run(Thread.java:761)

This is log what i can see in console log.

**Comment by felixkm** [comment]
This is intentional so developers can react to users canceling authentication. You're encouraged to catch this exception and handle it appropriately.
