### ISSUE TITLE
CloudRail fails to upload files over 10MB to Dropbox and OneDrive

### ISSUE THREAD

**Issue by jaredrummler** [CloudRail/cloudrail-si-android-sdk#79]
Uploading files over 10MB fail with `read: unexpected EOF!` for Dropbox and OneDrive.

### Actual Behavior:

CloudRail continues to read from the InputStream and never finishes when a file is over 10MB

### Expected behavior:

CloudRail should successfully upload the file.

### Reproduction Steps:

Login to Dropbox or OneDrive using CloudRail and run the following:

```java
Dropbox dropbox = ...
Runnable runnable = new CloudRailUploadTest(dropbox, context);
new Thread(runnable).start();
```

##### CloudRailUploadTest:

```java

import android.content.Context;
import android.support.annotation.NonNull;
import android.util.Log;
import com.cloudrail.si.interfaces.CloudStorage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.RandomAccessFile;

/**
 * Creates a temp file that is 10MB and attempts to upload the file to the provided cloud storage.
 * CloudRail fails with "read: unexpected EOF!" and upload continues forever.
 * If the size of the file is under 10MB the file is uploaded successfully.
 */
public class CloudRailUploadTest implements Runnable {

  private static final String TAG = "CloudRailUploadTest";

  private final CloudStorage cloudStorage;
  private final Context context;
  int progress;

  public CloudRailUploadTest(CloudStorage cloudStorage, Context context) {
    this.cloudStorage = cloudStorage;
    this.context = context;
  }

  @Override public void run() {
    try {
      // temp file to upload
      File temp = new File(context.getFilesDir(), String.valueOf(System.nanoTime()));

      // create a file over 10MB
      try {
        RandomAccessFile raf = new RandomAccessFile(temp, "rw");
        raf.setLength(10 * 1024 * 1024); // over 10MB causes "read: unexpected EOF!"
      } catch (FileNotFoundException e) {
        e.printStackTrace();
      }

      final long length = temp.length();

      Log.d(TAG, "temp length: " + length);

      ProgressInputStream inputStream = new ProgressInputStream(
          new FileInputStream(temp),
          new ProgressListener() {
            @Override public void onProgressChanged(long numBytes, long totalBytes) {
              int progress = (int) (numBytes * 100 / totalBytes);
              if (CloudRailUploadTest.this.progress != progress) {
                Log.d(TAG, "onProgressChanged: " + progress);
                CloudRailUploadTest.this.progress = progress;
              }
              Log.d(TAG,
                  "onProgressChanged() called with: numBytes = [" + numBytes + "], totalBytes = [" + totalBytes + "]");
            }
          },
          length
      );

      try {
        cloudStorage.upload("/large_file.test", inputStream, length, true);
      } finally {
        inputStream.close();
        temp.delete();
      }

    } catch (IOException e) {
      e.printStackTrace();
    }
  }

  /**
   * The listener interface for monitoring the progress of a long-running API call.
   */
  public interface ProgressListener {

    /**
     * Invoked when the progress of the API call changes.
     *
     * @param numBytes
     *     the number of bytes completed.
     * @param totalBytes
     *     the total number of bytes.
     */
    void onProgressChanged(long numBytes, long totalBytes);

  }

  /**
   * An {@link InputStream} that can report the progress of reading from another InputStream to a
   * {@link ProgressListener}.
   */
  public static class ProgressInputStream extends InputStream {

    private final InputStream stream;
    private final ProgressListener listener;

    private long total;
    private long totalRead;

    /**
     * Constructs a ProgressInputStream that wraps another InputStream.
     *
     * @param stream
     *     the stream whose progress will be monitored.
     * @param listener
     *     the listener that will receive progress updates.
     * @param total
     *     the total number of bytes that are expected to be read from the stream.
     */
    public ProgressInputStream(InputStream stream, ProgressListener listener, long total) {
      this.stream = stream;
      this.listener = listener;
      this.total = total;
    }

    /**
     * Gets the total number of bytes that are expected to be read from the stream.
     *
     * @return the total number of bytes.
     */
    public long getTotal() {
      return this.total;
    }

    /**
     * Sets the total number of bytes that are expected to be read from the stream.
     *
     * @param total
     *     the total number of bytes
     */
    public ProgressInputStream setTotal(long total) {
      this.total = total;
      return this;
    }

    @Override public void close() throws IOException {
      this.stream.close();
    }

    @Override public int read() throws IOException {
      int read = this.stream.read();
      this.totalRead++;
      this.listener.onProgressChanged(this.totalRead, this.total);
      return read;
    }

    @Override public int read(@NonNull byte[] b, int off, int len) throws IOException {
      int read = this.stream.read(b, off, len);
      this.totalRead += read;
      this.listener.onProgressChanged(this.totalRead, this.total);
      return read;
    }
  }

}

```

**Comment by PatrickStoklasa** [comment]
Hey Jared,

I will take a look at it and see if I can reproduce the error. Thanks for bringing it up!

**Comment by PatrickStoklasa** [comment]
I could not confirm the above issue so far. All our test cases test files with various sizes including files bigger than 10MB. Does this happen for every file of that size or just a specific file? Could you maybe share (via email) the exact file you tried so I can verify the behavior?

**Comment by jaredrummler** [comment]
I had some more time to look into this. I was reporting the progress wrong. 

For larger files, the file is read character by character for Dropbox and OneDrive. This makes uploading large files very slow. Is it possible to change this?

**Comment by PatrickStoklasa** [comment]
I deeply looked into our implementation but could not find a difference in how we handle the upload for Dropbox / OneDrive as opposed to other services. If I look into the standard implementation of a Java InputStream, even if you supply a buffer to read data into, the stream would still call the read method for every byte it is trying to read. This to me appears as reading character by character is the standard behavior of an InputStream.
So if you experience a significant difference in upload speed there might be something else that is causing it on our side, or maybe those service are just not as fast as the others. Could you share some of your insights in uploading speed to get a better idea?

**Comment by jaredrummler** [comment]
> If I look into the standard implementation of a Java InputStream, even if you supply a buffer to read data into, the stream would still call the read method for every byte it is trying to read. This to me appears as reading character by character is the standard behavior of an InputStream.

When uploading files to Dropbox and OneDrive _under_ 10MB `read(@NonNull byte[] b, int off, int len)` is only called. If the file is 10MB or larger than `read()` is called. Please test this again on Android.

**Comment by donpwilson** [comment]
I don't know whether this might help but I tested uploading a file (photo) > 10Mb to OneDrive using my app. It failed with the following error message:

```
03-10 13:15:30.124 25584-25710/com.dpw.photoplayer I/Job_Copy_Move_Photos: job-manager onCancel() 5
                                                                           java.lang.RuntimeException: ServiceCode Error in function chunkedAppend at 10: http.requestCall $L5 $L0 
                                                                               at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:127)
                                                                               at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45)
                                                                               at com.cloudrail.si.services.OneDrive.upload(OneDrive.java:1192)
                                                                               at com.dpw.photoplayer.My_Service.upload(My_Service.java:215)
                                                                               at com.dpw.photoplayer.jobs.Job_Copy_Move_Photos.onRun(Job_Copy_Move_Photos.java:177)
                                                                               at com.birbit.android.jobqueue.Job.safeRun(Job.java:229)
                                                                               at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132)
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:407)
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:326)
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:354)
                                                                               at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36)
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:389)
                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                            Caused by: javax.net.ssl.SSLException: Write error: ssl=0x9dce29c0: I/O error during system call, Connection timed out
                                                                               at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
                                                                               at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:771)
                                                                               at com.android.okhttp.okio.Okio$1.write(Okio.java:76)
                                                                               at com.android.okhttp.okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
                                                                               at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
                                                                               at com.android.okhttp.okio.RealBufferedSink.write(RealBufferedSink.java:46)
                                                                               at com.android.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:302)
                                                                               at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
                                                                               at com.android.okhttp.okio.RealBufferedSink$1.write(RealBufferedSink.java:198)
                                                                               at com.android.tools.profiler.support.network.HttpTracker$OutputStreamTracker.write(HttpTracker.java:155)
                                                                               at com.cloudrail.si.servicecode.commands.http.RequestCall.execute(RequestCall.java:121)
                                                                               at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:87)
                                                                               at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45) 
                                                                               at com.cloudrail.si.services.OneDrive.upload(OneDrive.java:1192) 
                                                                               at com.dpw.photoplayer.My_Service.upload(My_Service.java:215) 
                                                                               at com.dpw.photoplayer.jobs.Job_Copy_Move_Photos.onRun(Job_Copy_Move_Photos.java:177) 
                                                                               at com.birbit.android.jobqueue.Job.safeRun(Job.java:229) 
                                                                               at com.birbit.android.jobqueue.JobHolder.safeRun(JobHolder.java:132) 
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer.handleRunJob(ConsumerManager.java:407) 
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer.access$000(ConsumerManager.java:326) 
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer$2.handleMessage(ConsumerManager.java:354) 
                                                                               at com.birbit.android.jobqueue.messaging.SafeMessageQueue.consume(SafeMessageQueue.java:36) 
                                                                               at com.birbit.android.jobqueue.ConsumerManager$Consumer.run(ConsumerManager.java:389) 
                                                                               at java.lang.Thread.run(Thread.java:818) 
```
Uploading the same file to Box worked.

**Comment by pliratu** [comment]
I can can confirm both, @donpwilson and @jaredrummler. Exact same behavior here (OneDrive).

**Comment by pliratu** [comment]
And this is really a major issue, cause we can't provide OneDrive and Dropbox with this serious issue. And it is exact as @jaredrummler describes it.

**Comment by PatrickStoklasa** [comment]
I see that this appears to be a major issue and we are running a couple more tests at the moment. However, we have not been able to reproduce the issue @jaredrummler or @donpwilson was referring to. The former seemed to be an issue in the implementation of the progress reporting not in our SDK so which of the issues are you having @pliratu?
