### ISSUE TITLE
com.cloudrail.si.exceptions.HttpException on FileViewer

### ISSUE THREAD

**Issue by xbandx68** [CloudRail/cloudrail-si-android-sdk#88]
I'm try to test your example, but I return this error

09-29 22:04:30.725 9988-10074/com.cloudrail.fileviewer E/AndroidRuntime: FATAL EXCEPTION: Thread-231
                                                                         Process: com.cloudrail.fileviewer, PID: 9988
                                                                         com.cloudrail.si.exceptions.HttpException: {"error": "invalid_client: Invalid client_id or client_secret"}
                                                                             at com.cloudrail.si.services.Dropbox.getAllocation(Dropbox.java:1215)
                                                                             at com.cloudrail.fileviewer.Files$1.run(Files.java:167)
                                                                             at java.lang.Thread.run(Thread.java:818)

**Comment by PatrickStoklasa** [comment]
Hi there,

You need to replace the placeholders in the Services.java with your own credentials (client ID and client secret) otherwise it is not working. You can find more information here https://cloudrail.com/integrations/services/Dropbox . Go to "API Keys" for a step by step guide on how to obtain them.
