### ISSUE TITLE
Google Drive getMimeType error during instrumented Test

### ISSUE THREAD

**Issue by moifort** [CloudRail/cloudrail-si-android-sdk#90]
Hello Cloud Rail Team,

I am trying to upload document with Google Drive, but I have some trouble

## Environment
* **Library**: `com.cloudrail:cloudrail-si-android:2.20.2`
* **Android Studio**: `2.3.3`

## Error
```bash
java.lang.RuntimeException: ServiceCode Error in function uploadGD at 37: getMimeType $L28 $L29
at com.cloudrail.si.servicecode.Interpreter.run(Interpreter.java:127)
at com.cloudrail.si.servicecode.Interpreter.callFunction(Interpreter.java:45)
at com.cloudrail.si.services.GoogleDrive.upload(GoogleDrive.java:1301)
```
## Instrumented Test

```Kotlin
@RunWith(AndroidJUnit4::class)
class GoogleDriveWriterTest {

    @Test
    fun should_save_file_on_google_drive() {
        // Given
        CloudRail.setAppKey("MyCloudRailAPI")
        val book = jpegByteArrayFromResource(R.drawable.book)
        val stream = ByteArrayInputStream(book)
        val applicationId = "MyApplicationId"
        val googleDrive = GoogleDrive(InstrumentationRegistry.getContext(),
                applicationId,
                "",
                "com.my.app.com:/auth",
                "state")
        googleDrive.useAdvancedAuthentication()
        googleDrive.loadAsString("""MyTokenSaveWithSaveAsString""")

        // When
        googleDrive.upload("/test.jpg", stream, book.size.toLong(), true)
    }

}
```

**Comment by moifort** [comment]
I figure out why, the problem is the API cannot find the file `MIMETypeMap` from the actual context.

## Solution

You should use `InstrumentationRegistry.getTargetContext()` instead of `InstrumentationRegistry.getContext()`

## Instrumented Test

```kotlin
@RunWith(AndroidJUnit4::class)
class GoogleDriveWriterTest {

    @Test
    fun should_save_file_on_google_drive() {
        // Given
        CloudRail.setAppKey("MyCloudRailAPI")
        val book = jpegByteArrayFromResource(R.drawable.book)
        val stream = ByteArrayInputStream(book)
        val applicationId = "MyApplicationId"
        val googleDrive = GoogleDrive(InstrumentationRegistry.getTargetContext(),
                applicationId,
                "",
                "com.my.app.com:/auth",
                "state")
        googleDrive.useAdvancedAuthentication()
        googleDrive.loadAsString("""MyTokenSaveWithSaveAsString""")

        // When
        googleDrive.upload("/test.jpg", stream, book.size.toLong(), true)
    }

}
```
